trigger:
- master

stages:
  - stage: BuildStage
    jobs:
      - job: basicBuildJob
        displayName: Build job with submodules
        pool: 
          vmImage: 'ubuntu-latest'
         
        

        steps: 
        - checkout: self
          submodules: recursive

        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              # find . |grep -v git 
              false


  - stage: DEVDeploymentStage
    condition: succeeded('BuildStage')

    jobs:
      - deployment: DevDep
        displayName: Deploy On Dev Environment
        pool:
          vmImage: 'ubuntu-latest'
        environment: DevEnv
        strategy:
          runOnce:
            deploy: 
              steps: 
              - script: echo "My deployment on Dev Env"
        

  - stage: QADeploymentStage
    condition: succeeded('BuildStage')

    jobs:
      - deployment: QADep
        displayName: Deploy On QA Environment
        pool:
          vmImage: 'ubuntu-latest'
        environment: QAEnv
        strategy:
          runOnce:
            deploy: 
              steps: 
              - script: echo "My deployment on QA Env"



         
 
                








