trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true
    submodules: recursive

    
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        find  . |grep -v git


