trigger:
- master

jobs:
  - job: basicBuild
    pool: 
     vmImage: 'ubuntu-latest'

    steps: 
    - checkout: self
      submodules: recursive

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          find . |grep -v git

  - deployment: onDevEnv
    pool:
      vmImage: 'ubuntu-latest'
    environment: DevEnv

  - deployment: onQAEnv
    pool:
      vmImage: 'ubuntu-latest'
    environment: QAEnv






