trigger:
- master

jobs:
  - job: basicBuild
    steps: 
    - checkout: self
      submodules: recursive

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          find . |grep -v git

  - deployment: 
    environment: DevEnv

  - deployment: 
    environment: QAEnv





