trigger:
- master

jobs:
  - job: basicBuild
    pool: 
     vmImage: 'ubuntu-latest'

    steps: 
    - checkout: self
      submodules: recursive

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          find . |grep -v git

  - deployment: onDevEnv
    dependsOn: basicBuild
    pool:
      vmImage: 'ubuntu-latest'
    environment: DevEnv
    strategy:
     runOnce:
        deploy:
          steps:
            - script: echo "hello world"

  - deployment: onQAEnv
    dependsOn: onDevEnv
    pool:
      vmImage: 'ubuntu-latest'
    environment: QAEnv
    strategy:
     runOnce:
        deploy:
          steps:
            - script: echo "hello world"
            








